name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir _build && cd _build && cmake ..
    - name: make
      run: cd _build && make -j
    - name: run tests
      run: cd _build && ctest
